version: '3.8'

services:
  postgres:
    image: postgres
    container_name: employees
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
